name: simple_barcode_scanner_flutterflow
description: Version of simple_barcode_scanner built for Flutterflow
version: 0.0.12-dev.2
homepage: https://github.com/treyhendon/simple_barcode_scanner
issue_tracker: https://github.com/treyhendon/simple_barcode_scanner/issues

platforms:
  android:
  ios:
  web:
  windows:

environment:
  sdk: ">=2.17.0 <=3.13.7"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  # Flutter window webview
  webview_windows: ^0.2.2
  # Barcode scanner for android and ios
  flutter_barcode_scanner: ^2.0.0
  #Get assets path for window platform
  path: ^1.8.2
  #checking permissions
  permission_handler: ^10.2.0
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.1

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:

  # To add assets to your package, add an assets section, like this:
  assets:
    - packages/simple_barcode_scanner_flutterflow/assets/barcode.html
    - packages/simple_barcode_scanner_flutterflow/assets/html5-qrcode.min.js
  #
  # For details regarding assets in packages, see
  # https://flutter.dev/assets-and-images/#from-packages
  #
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # To add custom fonts to your package, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts in packages, see
  # https://flutter.dev/custom-fonts/#from-packages
